# Custom Binds
bind=SUPERSHIFT, E, exit
bind=SUPERSHIFT,U,hyprload,update
bind=SUPER,RETURN,exec,$Term # Normal
bind=SUPER,B,exec, $Browser
bind=SUPER,E,exec,$Files
bind=SUPER,D,exec,$HOME/.config/hypr/binds/startWofi.sh
bind=SUPER,Q,killactive,
bind=SUPERSHIFT,E,exec,pkill Hyprland
bind=SUPERSHIFT,R,exec,hyprctl reload
bind=SUPER,space,togglefloating,
bind=SUPER,P, exec, wlogout
bind=ALTSHIFT, L, exec, swaylock
bind=SUPER,F,fullscreen
bind=ALTSHIFT,A,exec,amixer set 'Master' 5%+
bind=ALTSHIFT,D,exec,amixer set 'Master' 5%-
bind=SUPERSHIFT,N,exec, swaync-client -t -sw

bind=SUPERSHIFT,P,exec,grim ~/Screenshots/$(date +'%Y%m%d%H%M%S_1.png') | wl-copy -t image/png && notify-send 'Screenshot Saved'
bind=SUPERALTSHIFT, P, exec, grim -s ~/Screenshots/$(date +'%Y%m%d%H%M%S_1.png') -g "$(slurp)" - | wl-copy -t image/png && notify-send 'Screenshot Saved'

#Brightness
bind=SUPERSHIFT,J,exec,brightnessctl --device=intel_backlight s 5%-
bind=SUPERSHIFT,K,exec,brightnessctl --device=intel_backlight s 5%+
bind=SUPER, O, toggleopaque
