# Custom Binds
bind=SUPERSHIFT, E, exit
bind=SUPER,RETURN,exec,$Term # Normal
bind=SUPERSHIFT, RETURN, exec, foot
bind=SUPER,B,exec, $Browser
bind=SUPER,E,exec,$Files
bind=SUPER,D,exec,$HOME/.config/hypr/binds/startWofi.sh
bind=SUPER,Q,killactive,
bind=SUPERSHIFT,E,exec,pkill Hyprland
bind=SUPERSHIFT,R,exec,hyprctl reload
bind=SUPER,space,togglefloating,
bind=SUPER,P, exec, wlogout
bind=ALTSHIFT, L, exec, swaylock
bind=SUPER,F,fullscreen
bind=ALTSHIFT,A,exec,amixer set 'Master' 5%+
bind=ALTSHIFT,D,exec,amixer set 'Master' 5%-
bind=SUPERSHIFT,N,exec, swaync-client -t -sw
bind=SUPER, S, exec, imv ~/Pictures/samc.png

bind=SUPERSHIFT,P,exec,hyprshot -m region -o ~/Screenshot/
bind=SUPERALTSHIFT, P, exec, hyprshot -m window -o ~/Screenshot/

#Brightness
binde=,XF86MonBrightnessDown,exec,brightnessctl --device=intel_backlight s 5%-
binde=,XF86MonBrightnessUp,exec,brightnessctl --device=intel_backlight s 5%+
bind=SUPER, O, toggleopaque
