# Custom Binds
bind=SUPERSHIFT, E, exit
bind=SUPERSHIFT,U,hyprload,update
bind=SUPER,RETURN,exec,$Term # Normal
bind=SUPER,B,exec, $Browser
bind=SUPER,E,exec,$Files
bind=SUPER,D,exec,wofi --show drun -I
bind=SUPER,Q,killactive,
bind=SUPERSHIFT,E,exec,pkill Hyprland
bind=SUPERSHIFT,R,exec,hyprctl reload
bind=SUPER,space,togglefloating,
bind=SUPER,P, exec, wlogout
bind=ALTSHIFT, L, exec, swaylock --screenshots --clock --indicator --indicator-radius 100 --indicator-thickness 7 --effect-blur 7x5 --effect-vignette 0.5:0.5 --ring-color cc241d --key-hl-color fb4934 --line-color e1dbcd --inside-color fb4934cc --separator-color 00000000 --grace 2 --fade-in 0.2
bind=SUPER,F,fullscreen
bind=ALTSHIFT,A,exec,amixer set 'Master' 5%+
bind=ALTSHIFT,D,exec,amixer set 'Master' 5%-
bind=SUPERSHIFT,N,exec, swaync-client -t -sw

bind=SUPERSHIFT,P,exec,grim ~/Screenshots/$(date +'%Y%m%d%H%M%S_1.png') && notify-send 'Screenshot Saved'
bind=SUPERALTSHIFT, P, exec, scrot -s ~/Screenshots/$(date +'%Y%m%d%H%M%S_1.png') && notify-send 'Screenshot Saved'

#Brightness
bind=SUPERSHIFT,J,exec,brightnessctl --device=intel_backlight s 5%-
bind=SUPERSHIFT,K,exec,brightnessctl --device=intel_backlight s 5%+
bind=SUPER, O, toggleopaque
