decoration {
    blur_new_optimizations = true
    drop_shadow = false
    shadow_range= false
    shadow_render_power= false
    col.shadow= false
    col.shadow_inactive= false
    rounding=10
    blur= false
    blur_size= false # minimum 1
    blur_passes= false # minimum 1, more passes = more resource intensive.
}


exec=swaybg -m fill -i ~/Walls/gruvbox-wallpapers/wallpapers/mix/xavier-cuenca-w4-3.jpg
exec-once=swaync
exec-once=eww daemon &
exec-once=eww open bar0 &
exec-once=systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=/usr/lib/polkit-kde-authentication-agent-1
