exec-once=waybar
exec-once=nextcloud --background
exec-once=/usr/lib/polkit-kde-authentication-agent-1
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once=whatpulse
exec-once=swaync
exec-once=$HOME/.local/share/hyprload/hyprload.sh
exec-once=$HOME/.config/hypr/xdg-kill
