# Window Rules

windowrule = fullscreen, wlogout
windowrule = float, title:wlogout
windowrule = fullscreen, title:wlogout
windowrule = move 400 400, float, title:(jetbrains toolbox),
windowrule=float,wofi
windowrule=fullscreen,title:^(full)$

